// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyxprqbvhfpbzvtohqjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95eHBycWJ2aGZwYnp2dG9ocWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTg3NjYsImV4cCI6MjA2OTg5NDc2Nn0.P39Elsi0NpKHpKy6el6V_lG-PnJwmI-WK5QBwhlmD2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});